USE DOAN_HQTCSDL
GO

CREATE 
--alter
PROC sp_ThemVaoGioHang 
	@MAN_MA CHAR(10),
	@TD_MA CHAR(10),
	@CN_MA CHAR(10),
	@CH_MA CHAR(10),
	@KH_MA CHAR(10),
	@SOLUONG INT,
	@NOTES NVARCHAR(100)
AS
BEGIN TRANSACTION
SET TRAN ISOLATION LEVEL SERIALIZABLE
	BEGIN TRY
		IF NOT EXISTS(SELECT * FROM dbo.KHACHHANG WHERE KH_MA = @KH_MA)
		BEGIN 
			PRINT N'KHACH HANG KHONG TON TAI'
			ROLLBACK
		END
		IF NOT EXISTS (SELECT * FROM dbo.MONAN WHERE MAN_MA = @MAN_MA)
		BEGIN 
			PRINT N'MON AN KHONG TON TAI'
			ROLLBACK
		END 
		INSERT INTO dbo.GIOHANG
		(
		    MAN_MA,
		    TD_MA,
		    CN_MA,
		    CH_MA,
		    KH_MA,
		    SOLUONG,
		    NOTES
		)
		VALUES
		(   @MAN_MA,
			@TD_MA,
			@CN_MA,
			@CH_MA,
			@KH_MA,
			@SOLUONG,
			@NOTES
		    )
	END TRY
	BEGIN CATCH
		PRINT N'LOI INSERT'
		ROLLBACK
	END CATCH
COMMIT TRANSACTION
GO
--
CREATE 
--ALTER
PROC SP_KHDATHANG
	@kH_MA CHAR(10), 
	@PHUONGTHUCTHANHTOAN NVARCHAR(100)
AS
BEGIN TRAN
SET TRAN ISOLATION LEVEL SERIALIZABLE
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM dbo.KHACHHANG WHERE KH_MA = @kH_MA)
		BEGIN 
			PRINT N'KHACH HANG KHONG TON TAI'
			ROLLBACK
		END


		PRINT 'BAT DAU PROC DAT HANG'
		-- lay dia chi khach hang
		DECLARE @XA CHAR(10), @HUYEN CHAR(10), @TINH CHAR(10)
		SELECT @XA = DC_MAXA, @HUYEN = DC_MAHUYEN, @TINH = DC_MATINH  FROM dbo.KHACHHANG WHERE KH_MA = @KH_MA
		
		-- PHAN LOAI MON AN THEO CUA HANG
		DECLARE D CURSOR FOR SELECT DISTINCT MN.CH_MA FROM dbo.MONAN MN, dbo.GIOHANG GH WHERE GH.KH_MA = @KH_MA AND GH.MAN_MA = MN.MAN_MA
		OPEN D
		DECLARE @CH_MA CHAR(10) 
		FETCH NEXT FROM D INTO @CH_MA
		
		SELECT * FROM dbo.MONAN
		SELECT * FROM dbo.GIOHANG
		PRINT @CH_MA
		WHILE @@FETCH_STATUS = 0
		BEGIN
			-- MA DON HANG
			WAITFOR DELAY '00:00:10'
			DECLARE @DH_MA CHAR(10), @TMP INT;
			SELECT @TMP = COUNT(*) + 1 FROM dbo.DONHANG;
			SET @DH_MA = 'DH_' + CAST(@TMP AS CHAR(10));
			-- TONG TIEN
			DECLARE @TONGTIEN MONEY 
			SET @TONGTIEN = 0;
			-- INSERT DONHANG
			INSERT INTO dbo.DONHANG
			(
				DH_MA,
				DH_NGAYDAT,
				DH_PHUONGTHUCTHANHTOAN,
				DH_TONGTIEN,
				KH_MA,
				CH_MA,
				DH_PHIVANCHUYEN,
				DH_TINHTRANG,
				TX_MA,
				DC_MATINH,
				DC_MAHUYEN,
				DC_MAXA
			)
			VALUES
			(   @DH_MA,   -- DH_MA - char(10)
				GETDATE(), -- DH_NGAYDAT - datetime
				@PHUONGTHUCTHANHTOAN, -- DH_PHUONGTHUCTHANHTOAN - nvarchar(100)
				1000000, -- DH_TONGTIEN - money
				@KH_MA, -- KH_MA - char(10)
				@CH_MA, -- CH_MA - char(10)
				10000, -- DH_PHIVANCHUYEN - money
				N'Chưa xác nhân', -- DH_TINHTRANG - nvarchar(50)
				NULL, -- TX_MA - char(10)
				@TINH, -- DC_MATINH - char(10)
				@HUYEN, -- DC_MAHUYEN - char(10)
				@XA  -- DC_MAXA - char(10)
				)
			DECLARE C CURSOR FOR SELECT GH.MAN_MA, GH.SOLUONG, GH.NOTES FROM dbo.GIOHANG GH, dbo.MONAN MN
										WHERE KH_MA = @kH_MA AND MN.MAN_MA = GH.MAN_MA AND MN.CH_MA = @CH_MA

			OPEN C
			DECLARE @MAN_MA CHAR(10), @SOLUONG INT, @NOTES NVARCHAR(100)
			FETCH NEXT FROM C INTO @MAN_MA, @SOLUONG, @NOTES
			WHILE @@FETCH_STATUS = 0
				BEGIN
					PRINT @MAN_MA
					-- LAY THONG TIN MON AN
					DECLARE @TD_MA CHAR(10), @CN_MA CHAR(10), @GIA MONEY
					SELECT @TD_MA = TD_MA, @CN_MA = CN_MA, @GIA = MAN_GIA FROM dbo.MONAN WHERE MAN_MA = @MAN_MA 
					--TINH TONG TIEN
					SET @TONGTIEN = @TONGTIEN + @SOLUONG * @GIA
					PRINT @CH_MA + ' - ' + @MAN_MA 
					INSERT INTO dbo.CHITIETDONHANG
					(
						DH_MA,
						MAN_MA,
						TD_MA,
						CN_MA,
						CH_MA,
						CTDH_SOLUONG,
						CTDH_GIATIEN,
						CTDH_GHICHU
					)
					VALUES
					(   @DH_MA,   -- DH_MA - char(10)
						@MAN_MA, -- MAN_MA - char(10)
						@TD_MA, -- TD_MA - char(10)
						@CN_MA, -- CN_MA - char(10)
						@CH_MA, -- CH_MA - char(10)
						@SOLUONG, -- CTDH_SOLUONG - char(10)
						NULL, -- CTDH_GIATIEN - money
						@NOTES  -- CTDH_GHICHU - nvarchar(100)
						)
					PRINT 'CHEN THANH CONG'
					DELETE dbo.GIOHANG WHERE KH_MA = @kH_MA AND MAN_MA = @MAN_MA
					FETCH NEXT FROM C INTO @MAN_MA, @SOLUONG, @NOTES
				END
			CLOSE C
			DEALLOCATE C
			-- UPDATE TONG TIEN
			UPDATE dbo.DONHANG
			SET DH_TONGTIEN = @TONGTIEN
			WHERE DH_MA = @DH_MA
			PRINT 'UPDATE THANH CONG'
			--TIEP TUC VONG LAP MOI
			FETCH NEXT FROM D INTO @CH_MA
		END

		CLOSE D
		DEALLOCATE D

	END TRY
	BEGIN CATCH
		PRINT N'LOI THUC THI'
		CLOSE D
		DEALLOCATE D
		CLOSE C
		DEALLOCATE C
		ROLLBACK
	END CATCH
COMMIT TRANSACTION
GO 