USE DOAN_HQTCSDL
GO

----KHÓA NGOẠI
-- HOSODANGKY -> HOPDONG 1: CHITIETHOPDONG
ALTER TABLE HOSODANGKY
ADD CONSTRAINT FK_HOSODK_HOPDONG
FOREIGN KEY (HD_MA)
REFERENCES HOPDONG(HD_MA)

-- HOSODANGKY -> DOITAC 2: DANGKYCUAHANG
ALTER TABLE HOSODANGKY
ADD CONSTRAINT FK_HOSODK_DOITAC	
FOREIGN KEY (DT_MA)
REFERENCES DOITAC(DT_MA)

--HOSODANGKY -> NHANVIEN 3: KYHOPDONG
ALTER TABLE HOSODANGKY
ADD CONSTRAINT FK_HOSODK_NHANVIEN	
FOREIGN KEY (NV_MA)
REFERENCES NHANVIEN(NV_MA)

--NHANVIEN -> DIACHI 4: DIACHINHANVIEN
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)

--PHIHOAHONG -> DONHANG 5: NOPPHH
ALTER TABLE PHIHOAHONG
ADD CONSTRAINT FK_PHIHOAHONG_DONHANG
FOREIGN KEY (DH_MA)
REFERENCES DONHANG(DH_MA)

-- PHIHOAHONG -> NHANVIEN 6: THUPHH
ALTER TABLE PHIHOAHONG
ADD CONSTRAINT FK_PHIHOAHONG_NHANVIEN
FOREIGN KEY (NV_MA)
REFERENCES NHANVIEN(NV_MA)

-- CUAHANG -> DOITAC 7: SOHUU
ALTER TABLE CUAHANG
ADD CONSTRAINT FK_CUAHANG_DOITAC
FOREIGN KEY (DT_MA)
REFERENCES DOITAC(DT_MA)

--CHINHANH -> CUAHNANG 8: CHINHANHCON
ALTER TABLE CHINHANH
ADD CONSTRAINT FK_CHINHANH_CUAHANG
FOREIGN KEY (CH_MA)
REFERENCES CUAHANG(CH_MA)

--THUCDON -> CHINHANH 9: THUCDONCHINHANH
ALTER TABLE THUCDON
ADD CONSTRAINT FK_THUCDON_CHINHANH
FOREIGN KEY (CN_MA,CH_MA)
REFERENCES CHINHANH(CN_MA,CH_MA)

--MONAN -> THUCDON 10: CHITIETTHUCDON
ALTER TABLE MONAN
ADD CONSTRAINT FK_MONAN_THUCDON
FOREIGN KEY (TD_MA, CN_MA, CH_MA)
REFERENCES THUCDON(TD_MA, CN_MA, CH_MA)

--DONHANG -> CUAHANG 11: DONTHUOCCUAHANG
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_CUAHANG
FOREIGN KEY (CH_MA)
REFERENCES CUAHANG(CH_MA)

--DONHANG ->KHACHHANG 12: DATHANG
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_KHACHHANG
FOREIGN KEY (KH_MA)
REFERENCES KHACHHANG(KH_MA)

--CHITIETDONHANG -> DONHANG 13: CHITIETDONHANG
ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_DONHANG
FOREIGN KEY (DH_MA)
REFERENCES DONHANG(DH_MA)

--CHITIETDONHANG -> MONAN 14: MONANDUOCDAT ------------------LOI
ALTER TABLE CHITIETDONHANG
ADD CONSTRAINT FK_CHITIETDONHANG_MONAN
FOREIGN KEY (MAN_MA, TD_MA, CN_MA, CH_MA)
REFERENCES MONAN(MAN_MA, TD_MA, CN_MA, CH_MA)

--TINHTRANGGIAOHANG -> TAIXE 15: CAPNHAT_TTGH
ALTER TABLE TINHTRANGGIAOHANG
ADD CONSTRAINT FK_TINHTRANGGIAOHANG_TAIXE
FOREIGN KEY (TX_MA)
REFERENCES TAIXE(TX_MA)

--TINHTRANGGIAOHANG -> DONHANG 16: TINHTRANGCUADONHANG
ALTER TABLE TINHTRANGGIAOHANG
ADD CONSTRAINT FK_TINHTRANGGIAOHANG_KHACHHANG
FOREIGN KEY (DH_MA)
REFERENCES DONHANG(DH_MA)

--KHACHHANG-> DIACHI 17: DIACHIKHACHHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)

--TAIXE-> DIACHI 18: KHUVUCHOATDONG
ALTER TABLE TAIXE
ADD CONSTRAINT FK_TAIXE_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)


--TINHTRANGDONHANG-> DIACHI 19: VITRIHIENTAI---------LOI
ALTER TABLE TINHTRANGGIAOHANG
ADD CONSTRAINT FK_TINHTRANGGIAOHANG_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)

--HOPDONG -> NHANVIEN 20: DANGKY
ALTER TABLE HOPDONG
ADD CONSTRAINT FK_HOPDONG_NHANVIEN
FOREIGN KEY (NV_MA)
REFERENCES NHANVIEN(NV_MA)

--CHINHANH-> DIACHI 21: DIACHICHINHANH
ALTER TABLE CHINHANH
ADD CONSTRAINT FK_CHINHANH_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)

--DONHANG -> DIACHI 22: DIACHIGIAOHANG
ALTER TABLE DONHANG
ADD CONSTRAINT FK_DONHANG_DIACHI
FOREIGN KEY (DC_MATINH,DC_MAHUYEN,DC_MAXA)
REFERENCES DIACHI(DC_MATINH,DC_MAHUYEN,DC_MAXA)