CREATE 
--DROP
DATABASE DOAN_HQTCSDL
GO

USE DOAN_HQTCSDL
GO

CREATE
--ALTER
TABLE HOPDONG (
	HD_MA CHAR(10) PRIMARY KEY,
	HD_NGAYLAP DATETIME,
	HD_STK CHAR(20),
	HD_NGANHANG NVARCHAR(100),
	HD_CHINHANHNGANHANG NVARCHAR(100),
	HD_TINHTRANG NVARCHAR(50),
	HD_HOAHONG FLOAT
)
GO

CREATE 
--ALTER
TABLE HOSODANGKY (
	HSDK_MA CHAR(10) PRIMARY KEY,
	HD_MA CHAR(10), 
	HSDK_EMAIL NVARCHAR(50),
	HSDK_TENQUAN NVARCHAR(100),
	HSDK_THANHPHO NVARCHAR(50),
	HSDK_QUAN NVARCHAR(50),
	HSDK_SLCHINHANH INT,
	HSDK_SLDONHANGTOITHIEU INT,
	HSDK_LOAIAMTHUC NVARCHAR(100),
	HSDK_NGUOIDAIDIEN CHAR(10),
	HSDK_NVDK CHAR(10)
)
GO

CREATE 
--ALTER
TABLE DOITAC ( 
	DT_MA CHAR(10) PRIMARY KEY,
	DT_TEN NVARCHAR(50),
	DT_NGAYSINH DATE,
	DT_CMND CHAR(20),
	DT_SDT CHAR(10),
	DT_EMAIL NVARCHAR(100),
	--DIACHI
	DC_MATINH CHAR(10),
	DC_MAHUYEN CHAR(10),
	DC_MAXA CHAR(10),
)
GO

CREATE 
--ALTER
TABLE NHANVIEN (
	NV_MA CHAR(10),
	NV_TEN NVARCHAR(50),
	NV_NGAYSINH DATE,
	NV_CMND CHAR(20),
	NV_SDT CHAR(10),
	NV_MAIL NVARCHAR(100),
	--DIACHI
	DC_MATINH CHAR(10),
	DC_MAHUYEN CHAR(10),
	DC_MAXA CHAR(10),
) 
GO

CREATE
--ALTER
TABLE PHIHOAHONG (
	DT_MA CHAR(10) PRIMARY KEY,
	PHH_TONGTIEN MONEY,
	PHH_NGAYNOP DATETIME,
	PHH_PHITHANG DATE, -- NOP TIEN CHO THANG ... NAM ...
	PHH_NVNHAN CHAR(10)
)
GO

CREATE 
--ALTER
TABLE CUAHANG (
	CH_MA CHAR(10) PRIMARY KEY,
	DT_MA CHAR(10),
	CH_TEN CHAR(10), 
	CH_TGMOCUA TIME,
	CH_TGDONGCUA TIME,
	CH_TINHTRANGHOATDONG NVARCHAR(50)
)
GO

CREATE 
--ALTER
TABLE CHINHANH (
	CN_MA CHAR(10) PRIMARY KEY, 
	CH_MA CHAR(10),
	CN_DIACHI CHAR(10),
	CN_TEN NVARCHAR(100)
)
GO

CREATE 
--ALTER
TABLE THUCDON (
	TD_MA CHAR(10) PRIMARY KEY,		
	CN_MA CHAR(10), 
	CH_MA CHAR(10),
	TD_TEN CHAR(10)
)
GO

CREATE 
--ALTER
TABLE MONAN (
	MAN_MA CHAR(10) PRIMARY KEY,
	TD_MA CHAR(10),
	CN_MA CHAR(10), 
	CH_MA CHAR(10),
	MAN_TEN NVARCHAR(100),
	MAN_MIEUTA NVARCHAR(100),
	MAN_TINHTRANG NVARCHAR(20),
	MAN_GIA MONEY
)
GO

CREATE
--ALTER
TABLE DONHANG (
	DH_MA CHAR(10) PRIMARY KEY,
	DH_NGAYDAT DATETIME,
	DH_DIACHIGIAOHANG CHAR(10),
	DH_PHUONGTHUCTHANHTOAN NVARCHAR(100),
	DH_TONGTIEN MONEY,
	KH_MA CHAR(10),
	CH_MA CHAR(10)
)
GO

CREATE
--ALTER
TABLE CHITIETDONHANG (
	DH_MA CHAR(10),
	MAN_MA CHAR(10),
	CTDH_SOLUONG INT,
	CTDH_GHICHU NVARCHAR(100)
)
GO

CREATE
--ALTER
TABLE TAIXE (
	TX_MA CHAR(10) PRIMARY KEY,
	TX_TEN NVARCHAR(10),
	TX_CMND CHAR(20),
	TX_SDT CHAR(10),
	TX_BIENSOXE CHAR(10),
	TX_STK CHAR(20),
	TX_NGANHANG NVARCHAR(100),
	--DIACHI
	DC_MATINH CHAR(10),
	DC_MAHUYEN CHAR(10),
	DC_MAXA CHAR(10),
)
GO

CREATE 
--ALTER 
TABLE KHACHHANG (
	KH_MA CHAR(10) PRIMARY KEY,
	KH_TEN NVARCHAR(10),
	KH_SDT CHAR(10),
	KH_MAIL CHAR(10),
	--DIACHI
	DC_MATINH CHAR(10),
	DC_MAHUYEN CHAR(10),
	DC_MAXA CHAR(10),
)
GO

CREATE
--ALTER
TABLE DIACHI (
	DC_MATINH CHAR(10),
	DC_MAHUYEN CHAR(10),
	DC_MAXA CHAR(10),
	DC_TENTINH NVARCHAR(20),
	DC_TENHUYEN NVARCHAR(20),
	DC_TENXA NVARCHAR(20),
	DC_SONHA NVARCHAR(100),
)
GO
